<a href="https://colab.research.google.com/github/Soumya98-dev/MachineLearning-Course/blob/main/MachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Overview of machine learning

## Supervised
 - Maps Input(X) to Output(Y)
 - Regression
    - Predict a number from infintely many possible outputs
  - Classification
    - Predict categories from small number of possible outputs

## Unsupervised
  - finding something interesting in an unlabeled data
  - Clustering
    - group related stuff together
  - Anomaly deterction
    - find unusual data points
  - Dimensionality reduction
    - compress data using fewer numbers






# Machine Learning Process

## Data- Preprocessing
  - Import the data
  - Clean the data
  - Split into training & test sets

## Modelling
  - Build the model
  - train the model
  - make predictions

## Evaluation
  - Calculate performance metrics
  - make a verdict

## Training & Test data
  From the whole data only 20% of the data from the original dataset we take as a test data
  ***Train(80%), Test(20%)***

## Feature Scaling
  - Always applied to columns; never to data inside a row
  - Normalization
    - Taking the minimum in the column
    - subtracting that minimum from every single value inside that column
    - then dividing by the diference between the max & min
    - X' = X - X(min) / X(max) - X(min)
   - Standardization
    - Subtract the avg
    - X' = X - meu / sigma

## Data Preprocessing
  - Importing the libraries
  ```py
    import numpy as mp
    import matplotlib.pyplot as plt
    import pandas as pd
  ```
    - numpy -> arrays
    - matplotlib - plot charts
    - pandas - create matrix, dependent variable vector ,...
  - Importing datset
  - features(independent variable) are the columns with which we are going to predict the dependent variable.
  - iloc: all the rows
    - create a dataframe first
      ```py
        dataset = pd.read_csv('Data.csv')
        # taking all the columns
        #iloc is a method in pandas that allows you to select rows and columns in a DataFrame using integer-based indexing
        #:, -> from 0 and :-1(excluding -1) -> till last item
        # X is only the features(independent variable)
        X = dataset.iloc[:, :-1].values
        # only the last column(dependent variable)
        y = dataset.iloc[:, -1].values
      ```





# Coding Exercise 1: Importing and Preprocessing a Dataset for Machine Learning

In [1]:
#Importing the libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


In [2]:
#importing the dataset(iris)
dataset = pd.read_csv('Iris.csv')

In [3]:
#Creating the matrix of features (X) and the dependent variable vector (y)
#features (independent variables) in the Iris dataset are the lengths and widths
#of the petals and sepals, and the dependent variable is the species of the Iris.
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


In [4]:
print(X)
print(y)

[[1.00e+00 5.10e+00 3.50e+00 1.40e+00 2.00e-01]
 [2.00e+00 4.90e+00 3.00e+00 1.40e+00 2.00e-01]
 [3.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [4.00e+00 4.60e+00 3.10e+00 1.50e+00 2.00e-01]
 [5.00e+00 5.00e+00 3.60e+00 1.40e+00 2.00e-01]
 [6.00e+00 5.40e+00 3.90e+00 1.70e+00 4.00e-01]
 [7.00e+00 4.60e+00 3.40e+00 1.40e+00 3.00e-01]
 [8.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01]
 [9.00e+00 4.40e+00 2.90e+00 1.40e+00 2.00e-01]
 [1.00e+01 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [1.10e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [1.20e+01 4.80e+00 3.40e+00 1.60e+00 2.00e-01]
 [1.30e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01]
 [1.40e+01 4.30e+00 3.00e+00 1.10e+00 1.00e-01]
 [1.50e+01 5.80e+00 4.00e+00 1.20e+00 2.00e-01]
 [1.60e+01 5.70e+00 4.40e+00 1.50e+00 4.00e-01]
 [1.70e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.80e+01 5.10e+00 3.50e+00 1.40e+00 3.00e-01]
 [1.90e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [2.00e+01 5.10e+00 3.80e+00 1.50e+00 3.00e-01]
 [2.10e+01 5.40e+00 3.40e+00 1.70e+00 2.